version: '3.5'

services:
  backend:
    #image: "commonspub/commonspub:stable" # use stable/production/master release of backend
    image: 'commonspub/commonspub:latest' # uncomment to use unstable/staging/develop backend branch
    # You can also build your own backend image from the source or deploy in other ways
    restart: always
    ports:
      - '4000:4000'
      - '81:80'
    env_file:
      - .env
      - .env.secrets
    depends_on:
      - db
      - search
    volumes:
      - type: bind
        source: ./uploads
        target: /var/www/uploads
  frontend:
    build:
      context: .
    #      dockerfile: "Dockerfile"
    restart: always
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./Caddyfile2
        target: /etc/caddy/Caddyfile
        read_only: true
      - type: bind
        source: ./uploads
        target: /frontend/uploads
  db:
    image: postgres:9.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    env_file:
      - .env
      - .env.secrets
  search:
    image: getmeili/meilisearch
    ports:
      - '7707:7700'
    volumes:
      - './data/search:/data.ms'

volumes:
  postgres_data:
